name: CI Pipeline

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    # Step 3: Install Dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Run Linting
    - name: Run Linter
      run: npm run lint

    # Step 5: Run Tests
    - name: Run Tests
      run: npm test

    # Step 6: Build Project
    - name: Build Project
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    # Step 1: Checkout Code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Deploy Application
    - name: Deploy to Production
      run: |
        echo "Deploying application..."
        # Add your deployment commands here
